#!/usr/bin/env bash
set -ev
ENV=$1
copy=$2
if [[ "$ENV" == "" ]]; then
  ENV=dev
fi
doppler run --project swarm --config "$ENV" --command "VITE_BUILD_ENTRY=pixel-js pnpm vite build"
doppler run --project swarm --config "$ENV" --command "VITE_BUILD_ENTRY=pixel-v2 pnpm vite build"
if [[ "$copy" == "--copy" ]]; then
  doppler run --project swarm --config "$ENV" -- scripts/upload_to_s3 dist/pixel-js.js
  doppler run --project swarm --config "$ENV" -- scripts/upload_to_s3 dist/pixel-v2.js
fi