#!/usr/bin/env bash
set -ev
# get filename from $1, default to ./dist/pixel-js.js
filename=${1:-./dist/pixel-v2.js}

if [ "$AWS_ACCESS_KEY_ID" == "" ]; then
  exit 0
fi

S3_BUCKET_NAME="beehiiv-adnetwork-$VITE_HEROKU_ENV"

echo "Uploading to S3 $S3_BUCKET_NAME..."
aws s3 cp "$filename" "s3://$S3_BUCKET_NAME" --acl public-read